### ISSUE TITLE
Secure? 🔓

### ISSUE THREAD

**Issue by BevanR** [devongovett/unplugin-parcel-macros#1]
Have you considered the security implications of allowing less-trusted third-party code to execute at both;

1. run-time, in browsers, where all code is execute in a locked-down sandbox, and now;
2. build-time, where code is often expected to be highly trusted, and may have access to deployment keys and other secrets?

Are any of [Bun.js's security considerations and limitations](https://bun.sh/blog/bun-macros#security-considerations) applied to this plug-in?

**Comment by devongovett** [comment]
Yes, as mentioned in [the docs](https://parceljs.org/features/macros/), macros cannot be called from inside `node_modules`. So they can only be called from your own source code.
