### ISSUE TITLE
This library vs unplugin-macros

### ISSUE THREAD

**Issue by husayt** [devongovett/unplugin-parcel-macros#2]
Hi I am trying to understand how two libraries compare? Just to better understand usecases for both.

Here is the link to [unplugin-macros](https://github.com/unplugin/unplugin-macros)

Thank you

**Comment by husayt** [comment]
I found this. Is it accurate for these two libraries as well? 

https://parceljs.org/features/macros/#:~:text=Differences%20from%20Bun&text=Parcel%20supports%20returning%20functions%20from,Response%20objects%2C%20or%20Blob%20objects.

**Comment by devongovett** [comment]
Yes those are all true. Returning functions and generating assets are the main things. However, unplugin-macros has very limited evaluation support as well. I believe the arguments and return value must be literals (eg strings and numbers), not objects/arrays, and there is no support for evaluating constants either.
