### ISSUE TITLE
Issue with esbuild

### ISSUE THREAD

**Issue by pt7892** [devongovett/unplugin-parcel-macros#4]
Getting this error with esbuild - `Cannot create property 'sourcesContent' on string`. I checked wheres the issue, and it looks like its comming from here https://github.com/unjs/unplugin/blob/v1.8.3/src/esbuild/utils.ts#L192. Result from `unplugin-parcel-macros` is `{ code: string; map: string }` while `unplugin` expects `map` to be `SourceMap` 
```ts
interface SourceMap {
	file: string;
	mappings: string;
	names: string[];
	sources: string[];
	sourcesContent?: string[];
	version: number;
	toString(): string;
	toUrl(): string;
}
```

**Comment by devongovett** [comment]
hmm this may be a bug in unplugin. The types [here](https://github.com/unjs/unplugin/blob/main/src/types.ts#L39) include `SourceMapInput` which can be a string. It also works with other bundlers.

**Comment by pt7892** [comment]
Yeah, looks like its unplugins issue, they're not handling string case. https://github.com/unjs/unplugin/blob/main/src/esbuild/index.ts#L271-L290 

Will open issue there, thx
