### ISSUE TITLE
Include examples using React, TypeScript, etc

### ISSUE THREAD

**Issue by schontz** [devongovett/unplugin-parcel-macros#6]
Attempting to follow the instructions to add this on a vite project that has TS and React results build errors and type errors. More examples would be appreciated.

**Comment by devongovett** [comment]
Make sure you list the macros plugin first in your Vite config so it runs before other plugins. If that doesn't work I'll need an example so I can reproduce the problem.

**Comment by schontz** [comment]
Ah, that did the trick! Thank you.

A couple outstanding things:

1. My project uses aliases, e.g., `import { foo } from '@/foo'`. Macros don't pick up on alias resolution, though I do provide them to the vite config via [resolve.alias](https://vitejs.dev/config/shared-options#resolve-alias). If I manually change them to relative paths they work.
2. TypeScript does not understand the `with { type: 'macro' }` syntax. Perhaps I need a newer version? I'm running 4.9.x.

If these are real issues I can make new issues for them and provide some basic examples.

Thanks again.

**Comment by devongovett** [comment]
1. Yeah currently it just uses node's resolution, it won't go through vite to resolve macros. Not sure if there's a way to do that.
2. Yeah TS 5.3 and newer support import attributes

**Comment by schontz** [comment]
While not ideal, node resolution will work. It seems to me that many macros need a "double import" to really be useful anyway. Something like so:

```javascript
// expensive.js
export function expensiveOperation() { ... }

// first.js
import { expensiveOperation } from './expensive' with { type: 'macro' };
export const computedValue = expensiveOperation();

// others can now import w/o thinking about macros
import { computedValue } from './first';
```
